Feature/profile page
Artikool5/webbee-test-frontend pull request #1
Opened 2024-07-02 11:34 UTC by Artikool5

![image](https://github.com/Artikool5/webbee-test-frontend/assets/105431759/d082f341-e157-440d-b9b5-1ad3106dab83)
![image](https://github.com/Artikool5/webbee-test-frontend/assets/105431759/c5bd4362-1f4e-43bf-a60e-4164630c65d0)

![image](https://github.com/Artikool5/webbee-test-frontend/assets/105431759/4d0e03fa-ab34-4054-b9bc-9f73805500d0)
![image](https://github.com/Artikool5/webbee-test-frontend/assets/105431759/a9d82022-ac12-48cf-ab80-d3be068e7e09)

![image](https://github.com/Artikool5/webbee-test-frontend/assets/105431759/72297e7c-35bd-4042-8f9f-872cada871f0)

2024-07-02 12:23 UTC, heyanniemoran commented
gh pages: https://artikool5.github.io/webbee-test-frontend/

2024-07-02 12:25 UTC, heyanniemoran commented
![chrome_mjEm2S998y](https://github.com/Artikool5/webbee-test-frontend/assets/28657911/93bffa4d-06bc-4745-93b8-56f1e3c6671a)

Страничка пляшет

2024-07-02 12:27 UTC, Mary-fox commented
Пока первое на что обратила внимание...  

> Почему отдельные странички сделаны в js формате,попробуй переделать в html? 

> Сделай роутинг без хешей

2024-07-02 12:28 UTC, heyanniemoran commented
Понимаю, конечно, что макет на 1440px или сколько там, но обычно имеют в виду, что header и footer растягиваются на всю ширину
![image](https://github.com/Artikool5/webbee-test-frontend/assets/28657911/8e8f9e8d-c90e-4f1b-97bd-0596e61eb892)

2024-07-02 12:32 UTC, Mary-fox commented
Не вижу выполнения этого пункта -Сайт должен адекватно отображаться на типичных разрешениях экрана (телефон, планшет, десктоп).

2024-07-02 12:36 UTC, heyanniemoran commented on script.js
> +  const pageName = window.location.hash.slice(1) || "profile";
Надо делать не через hash. У нас же странички, а не блоки с якорями, к которым мы стучимся через #

2024-07-02 12:36 UTC, heyanniemoran commented on index.html
> +                        <div class="icon-wrapper icon-wrapper_sm"><img src="assets/icons/back-icon.svg" /></div>
Не забываем alt

2024-07-02 12:36 UTC, heyanniemoran commented on index.html
> +                    <div class="breadcrumbs">
Это не хлебные крошки, а меню. 
Хлебные крошки это вот это:
![image](https://github.com/Artikool5/webbee-test-frontend/assets/28657911/0155bf8e-11c2-4382-825d-80485a89c8f3)

2024-07-02 12:36 UTC, heyanniemoran commented on index.html
> +                                <a class="header-nav__link" href="#" data-page="profile">
Надо, чтоб была реальная ссылка и не было атрибута data-page

2024-07-02 12:39 UTC, Mary-fox commented on script.js
> +// Page scripts
попробуй переделать с new Date(), тк setInterval накапливает ошибку и может кривовато работать

2024-07-02 12:48 UTC, Artikool5 commented on index.html
> +                        <div class="icon-wrapper icon-wrapper_sm"><img src="assets/icons/back-icon.svg" /></div>
Разве иконкам нужно альтернативное описание?

2024-07-02 12:50 UTC, Artikool5 commented on index.html
> +                    <div class="breadcrumbs">
Ну да. Там даже разделитель есть, я просто и подумал, что там подразумевались переходы.

2024-07-02 12:52 UTC, Artikool5 commented on script.js
> +// Page scripts
Не понял, про какую ошибку ты говоришь. С Date попробую, но там же все равно будет обновление раз в сколько-то времени, правильно я понимаю?

2024-07-02 13:02 UTC, Mary-fox commented on script.js
> +// Page scripts
setInterval же   вызывает функцию через указанные интервалы времени, но если вспомнить eventloop, то могут образовываться задержки.Эти погрешности накапливаются, вызывая неточность результата. А если ты будешь использовать new Date,то эту проблему избежишь

2024-07-03 07:10 UTC, Mary-fox commented on index.html
> +                        <div class="icon-wrapper icon-wrapper_sm"><img src="assets/icons/back-icon.svg" /></div>
alt является обязательным атрибутом img. Не важно иконку ты туда прокидываешь или картинку)

2024-07-03 12:26 UTC, Artikool5 commented on index.html
> +                        <div class="icon-wrapper icon-wrapper_sm"><img src="assets/icons/back-icon.svg" /></div>
Спасибо за наводку. Действительно, альтернативный текст должен быть на всех тегах img, в зависимости от функционала иконки этот текст может быть просто пустой строкой, но он должен быть. Я, наверное, даже слишком глубоко углубился в гугление...

2024-07-05 13:22 UTC, heyanniemoran commented
Чот плохо свернулось 
![image](https://github.com/Artikool5/webbee-test-frontend/assets/28657911/ffdefe55-4441-4690-9a9f-d51e63a449fd)

2024-07-08 07:36 UTC, Mary-fox commented on index.html
> +                    <div class="breadcrumbs">
не увидела исправления) Надо переделать)

2024-07-08 07:37 UTC, Mary-fox commented
![Снимок экрана 2024-07-08 103115](https://github.com/Artikool5/webbee-test-frontend/assets/89971822/d9ee138a-5e77-4bde-8558-f978f9892b8f)
Надо еще реализовать, чтобы работала кнопка "назад".

2024-07-08 09:31 UTC, Mary-fox approved these changes

2024-07-08 12:59 UTC, heyanniemoran approved these changes

2024-07-08 13:42 UTC, heyanniemoran requested changes

2024-07-08 13:42 UTC, heyanniemoran commented on pages/map.js
Нужно переделать на html

2024-07-08 13:42 UTC, heyanniemoran commented on styles/global.css
> +}
А такую вложенность разве можно в css?

2024-07-08 13:42 UTC, heyanniemoran commented on script.js
> +
Лучше вынести в другой файл, так как по сути тут только открытие/закрытие менюшки.

2024-07-09 16:29 UTC, Artikool5 commented on styles/global.css
> +}
Ну, работает. Сейчас можно в новых браузерах как я понимаю. Я просто подумал - пока есть возможность проверить как вложенность в чистом css работает.
PS - только сейчас увидел письмо на почте хотя уведомления стоят на телефоне :(

2024-07-09 16:37 UTC, heyanniemoran commented on styles/global.css
> +}
А, окей. Буду знать тогда. Я на чистом css давно не пишу.

2024-07-10 13:47 UTC, heyanniemoran commented on script.js
> +})();
Задание приняли, но лучше разделять. Зашел на страничку - загрузили, а не сразу всё тащить.

2024-07-10 13:48 UTC, heyanniemoran approved these changes

2024-07-10 13:52 UTC, heyanniemoran commented
Можно мержить

2024-07-10 16:19 UTC, merged